# Generated by Django 4.2.6 on 2023-10-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.IntegerField(unique=True)),
                ('bill_number', models.IntegerField(unique=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_file', models.FileField(upload_to='bills/')),
            ],
        ),
    ]
