# Generated by Django 4.2.6 on 2023-10-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BillReceipt',
        ),
    ]
