# Generated by Django 4.2.6 on 2023-10-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0006_bill_balance_delete_billreceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_amount',
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
