# Generated by Django 4.2.6 on 2023-10-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0007_remove_bill_balance_remove_payment_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
