# Generated by Django 4.2.6 on 2023-10-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0009_bill_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='due_date',
        ),
    ]
