# Generated by Django 4.2.6 on 2023-10-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0010_remove_bill_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='party_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bill_app.party'),
            preserve_default=False,
        ),
    ]
