# Generated by Django 4.2.6 on 2023-10-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0011_party_remove_bill_party_id_bill_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='party',
        ),
        migrations.AddField(
            model_name='bill',
            name='party_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Party',
        ),
    ]
