# Generated by Django 4.2.6 on 2023-10-19 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0012_remove_bill_party_bill_party_id_delete_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_app.party'),
        ),
    ]
