# Generated by Django 4.2.6 on 2023-10-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0013_party_alter_bill_party_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='party_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Party',
        ),
    ]
