# Generated by Django 4.2.6 on 2023-10-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0015_party_alter_bill_party_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='contact_information',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='party_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
